# Generated by Django 2.2.7 on 2019-12-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(help_text='url')),
                ('maliciousType', models.CharField(help_text='Malicious information of the url', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MininglistDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(help_text='url')),
                ('WebsiteName', models.TextField(help_text='website name of the url')),
            ],
        ),
    ]
